/*
 * File: app/view/Hero.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Kali.view.Hero', {
  extend: 'Ext.Container',
  alias: 'widget.hero',

  requires: [
    'Kali.view.HeroViewModel',
    'Ext.form.Panel',
    'Ext.form.FieldSet',
    'Ext.field.Text',
    'Ext.Button'
  ],

  viewModel: {
    type: 'hero'
  },
  layout: 'fit',

  items: [
    {
      xtype: 'formpanel',
      id: 'frmLogin',
      title: 'Directorio Kalí - Ankana',
      items: [
        {
          xtype: 'fieldset',
          items: [
            {
              xtype: 'textfield',
              id: 'usuario',
              label: 'Usuario'
            },
            {
              xtype: 'textfield',
              id: 'clave',
              label: 'Clave',
              inputType: 'password'
            },
            {
              xtype: 'container',
              margin: 15,
              layout: 'fit',
              items: [
                {
                  xtype: 'button',
                  handler: function(button, e) {
                    var u = Ext.getCmp('usuario').getValue();
                    var c = Ext.getCmp('clave').getValue();
                    var me = this;

                    if(u !== null && c !== null && (u.length + 1) > 1 && (c.length + 1) > 1)
                    {
                      Ext.Ajax.request
                      ({
                        url: BASE_URL + '/server/servicios/login',
                        method: 'GET',
                        params:{
                          u: u,
                          c: c
                        },
                        callback: function(opt,success,response)
                        {
                          if (success)
                          {
                            var data = Ext.JSON.decode(response.responseText);
                            ID_USUARIO = data.id_usuario;
                            NOMBRE = data.nombre;
                            LOGGED = true;
                            Ext.getCmp('frmLogin').reset();
                            me.up('main').setActiveItem(1);
                          }
                          else
                          Ext.Msg.alert('Error', 'Sus datos están incorrectos o no tiene permiso de acceder a esta aplicación');
                        }
                      });
                    }
                    else
                    {
                      Ext.Msg.alert('Error','Todos los campos son obligatorios');
                    }
                  },
                  iconAlign: 'right',
                  iconCls: 'x-fa fa-sign-in',
                  text: 'Ingresar'
                }
              ]
            }
          ]
        },
        {
          xtype: 'component'
        },
        {
          xtype: 'component',
          cls: 'hero-card-title',
          hidden: true,
          html: 'Sencha Devs'
        },
        {
          xtype: 'component',
          cls: 'hero-card-sub-title',
          hidden: true,
          html: 'Worldwide Sencha developers database.  Find <b><i>your</i></b> developer here.',
          padding: 10
        },
        {
          xtype: 'component'
        },
        {
          xtype: 'component',
          cls: 'dev-count',
          hidden: true,
          padding: 12,
          bind: {
            html: '<span class="dev-count-label">Devs:</span> <b>{devsCount}<b>'
          }
        }
      ]
    }
  ]

});