/*
 * File: app/view/MyDataForm.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Kali.view.MyDataForm', {
  extend: 'Ext.form.Panel',
  alias: 'widget.mydataform',

  requires: [
    'Kali.view.MyDataFormViewModel',
    'Kali.view.MyDataFormViewController',
    'Ext.TitleBar',
    'Ext.Button',
    'Ext.tab.Panel',
    'Ext.Label',
    'Ext.form.FieldSet',
    'Ext.field.Date',
    'Ext.picker.Date',
    'Ext.field.File'
  ],

  controller: 'mydataform',
  viewModel: {
    type: 'mydataform'
  },
  layout: 'fit',

  items: [
    {
      xtype: 'titlebar',
      docked: 'top',
      items: [
        {
          xtype: 'button',
          iconCls: 'x-fa fa-long-arrow-left',
          text: 'Integrantes',
          listeners: {
            tap: 'onBackListTap'
          }
        }
      ]
    },
    {
      xtype: 'container',
      layout: 'fit',
      items: [
        {
          xtype: 'tabpanel',
          items: [
            {
              xtype: 'container',
              iconCls: 'x-fa fa-id-card-o',
              items: [
                {
                  xtype: 'label',
                  html: '<b>Datos generales</b>',
                  margin: '5 0 0 12'
                },
                {
                  xtype: 'fieldset',
                  items: [
                    {
                      xtype: 'textfield',
                      label: 'Nombres'
                    },
                    {
                      xtype: 'textfield',
                      label: 'Apellidos'
                    },
                    {
                      xtype: 'textfield',
                      label: 'Teléfono'
                    },
                    {
                      xtype: 'datefield',
                      label: 'F. nacimiento',
                      picker: {
                        xtype: 'datepicker',
                        title: 'My Panel'
                      }
                    },
                    {
                      xtype: 'filefield',
                      label: 'Foto'
                    }
                  ]
                }
              ]
            },
            {
              xtype: 'container',
              iconCls: 'x-fa fa-id-card'
            },
            {
              xtype: 'container',
              iconCls: 'x-fa fa-shopping-cart'
            },
            {
              xtype: 'container',
              iconCls: 'x-fa fa-briefcase'
            }
          ]
        }
      ]
    }
  ]

});